# Generated by Django 3.0 on 2020-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('product_price', models.FloatField()),
                ('product_qnty', models.IntegerField()),
            ],
        ),
    ]
